//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// RecipeFullResponseModel defines model for RecipeFullResponseModel.
type RecipeFullResponseModel struct {
	Description   *string                 `json:"description"`
	Id            openapi_types.UUID      `json:"id"`
	Ingredients   []RecipeIngredientModel `json:"ingredients"`
	PortionNum    int32                   `json:"portion_num"`
	PortionString string                  `json:"portion_string"`
	Slug          string                  `json:"slug"`
	Steps         []RecipeStepModel       `json:"steps"`
	TimeActive    int32                   `json:"time_active"`
	TimeTaken     int32                   `json:"time_taken"`
	Title         string                  `json:"title"`
}

// RecipeIngredientModel defines model for RecipeIngredientModel.
type RecipeIngredientModel struct {
	Amount       float32            `json:"amount"`
	Id           openapi_types.UUID `json:"id"`
	IngredientId openapi_types.UUID `json:"ingredient_id"`
	Position     int32              `json:"position"`
	SectionName  *string            `json:"section_name,omitempty"`
}

// RecipeResponseModel defines model for RecipeResponseModel.
type RecipeResponseModel struct {
	Description   *string            `json:"description"`
	Id            openapi_types.UUID `json:"id"`
	PortionNum    int32              `json:"portion_num"`
	PortionString string             `json:"portion_string"`
	Slug          string             `json:"slug"`
	TimeActive    int32              `json:"time_active"`
	TimeTaken     int32              `json:"time_taken"`
	Title         string             `json:"title"`
}

// RecipeStepModel defines model for RecipeStepModel.
type RecipeStepModel struct {
	Description string             `json:"description"`
	Id          openapi_types.UUID `json:"id"`
	Position    int32              `json:"position"`
	SectionName *string            `json:"section_name,omitempty"`
}

// NotFound defines model for NotFound.
type NotFound struct {
	Error *string `json:"error,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /docs)
	GetDocs(w http.ResponseWriter, r *http.Request)

	// (GET /recipes)
	GetRecipes(w http.ResponseWriter, r *http.Request)

	// (GET /recipes/{slug})
	GetRecipesSlug(w http.ResponseWriter, r *http.Request, slug string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetDocs operation middleware
func (siw *ServerInterfaceWrapper) GetDocs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDocs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRecipes operation middleware
func (siw *ServerInterfaceWrapper) GetRecipes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRecipes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRecipesSlug operation middleware
func (siw *ServerInterfaceWrapper) GetRecipesSlug(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRecipesSlug(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/docs", wrapper.GetDocs)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/recipes", wrapper.GetRecipes)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/recipes/{slug}", wrapper.GetRecipesSlug)

	return m
}

type NotFoundJSONResponse struct {
	Error *string `json:"error,omitempty"`
}

type GetDocsRequestObject struct {
}

type GetDocsResponseObject interface {
	VisitGetDocsResponse(w http.ResponseWriter) error
}

type GetDocs200Response struct {
}

func (response GetDocs200Response) VisitGetDocsResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GetRecipesRequestObject struct {
}

type GetRecipesResponseObject interface {
	VisitGetRecipesResponse(w http.ResponseWriter) error
}

type GetRecipes200JSONResponse []RecipeResponseModel

func (response GetRecipes200JSONResponse) VisitGetRecipesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRecipesSlugRequestObject struct {
	Slug string `json:"slug"`
}

type GetRecipesSlugResponseObject interface {
	VisitGetRecipesSlugResponse(w http.ResponseWriter) error
}

type GetRecipesSlug200JSONResponse RecipeFullResponseModel

func (response GetRecipesSlug200JSONResponse) VisitGetRecipesSlugResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRecipesSlug404JSONResponse struct{ NotFoundJSONResponse }

func (response GetRecipesSlug404JSONResponse) VisitGetRecipesSlugResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /docs)
	GetDocs(ctx context.Context, request GetDocsRequestObject) (GetDocsResponseObject, error)

	// (GET /recipes)
	GetRecipes(ctx context.Context, request GetRecipesRequestObject) (GetRecipesResponseObject, error)

	// (GET /recipes/{slug})
	GetRecipesSlug(ctx context.Context, request GetRecipesSlugRequestObject) (GetRecipesSlugResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetDocs operation middleware
func (sh *strictHandler) GetDocs(w http.ResponseWriter, r *http.Request) {
	var request GetDocsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDocs(ctx, request.(GetDocsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDocs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDocsResponseObject); ok {
		if err := validResponse.VisitGetDocsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRecipes operation middleware
func (sh *strictHandler) GetRecipes(w http.ResponseWriter, r *http.Request) {
	var request GetRecipesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRecipes(ctx, request.(GetRecipesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRecipes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRecipesResponseObject); ok {
		if err := validResponse.VisitGetRecipesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRecipesSlug operation middleware
func (sh *strictHandler) GetRecipesSlug(w http.ResponseWriter, r *http.Request, slug string) {
	var request GetRecipesSlugRequestObject

	request.Slug = slug

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRecipesSlug(ctx, request.(GetRecipesSlugRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRecipesSlug")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRecipesSlugResponseObject); ok {
		if err := validResponse.VisitGetRecipesSlugResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
