/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShoppingListIndexRouteImport } from './routes/shopping-list/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as RecipeIndexRouteImport } from './routes/recipe/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as IngredientIndexRouteImport } from './routes/ingredient/index'
import { Route as RecipeAddIndexRouteImport } from './routes/recipe/add/index'
import { Route as RecipeSlugIndexRouteImport } from './routes/recipe/$slug/index'
import { Route as IngredientAddIndexRouteImport } from './routes/ingredient/add/index'
import { Route as IngredientSlugIndexRouteImport } from './routes/ingredient/$slug/index'
import { Route as RecipeSlugEditIndexRouteImport } from './routes/recipe/$slug/edit/index'
import { Route as IngredientSlugEditIndexRouteImport } from './routes/ingredient/$slug/edit/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingListIndexRoute = ShoppingListIndexRouteImport.update({
  id: '/shopping-list/',
  path: '/shopping-list/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeIndexRoute = RecipeIndexRouteImport.update({
  id: '/recipe/',
  path: '/recipe/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientIndexRoute = IngredientIndexRouteImport.update({
  id: '/ingredient/',
  path: '/ingredient/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeAddIndexRoute = RecipeAddIndexRouteImport.update({
  id: '/recipe/add/',
  path: '/recipe/add/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeSlugIndexRoute = RecipeSlugIndexRouteImport.update({
  id: '/recipe/$slug/',
  path: '/recipe/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientAddIndexRoute = IngredientAddIndexRouteImport.update({
  id: '/ingredient/add/',
  path: '/ingredient/add/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientSlugIndexRoute = IngredientSlugIndexRouteImport.update({
  id: '/ingredient/$slug/',
  path: '/ingredient/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeSlugEditIndexRoute = RecipeSlugEditIndexRouteImport.update({
  id: '/recipe/$slug/edit/',
  path: '/recipe/$slug/edit/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientSlugEditIndexRoute = IngredientSlugEditIndexRouteImport.update({
  id: '/ingredient/$slug/edit/',
  path: '/ingredient/$slug/edit/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ingredient/': typeof IngredientIndexRoute
  '/login/': typeof LoginIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/recipe/': typeof RecipeIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/shopping-list/': typeof ShoppingListIndexRoute
  '/ingredient/$slug/': typeof IngredientSlugIndexRoute
  '/ingredient/add/': typeof IngredientAddIndexRoute
  '/recipe/$slug/': typeof RecipeSlugIndexRoute
  '/recipe/add/': typeof RecipeAddIndexRoute
  '/ingredient/$slug/edit/': typeof IngredientSlugEditIndexRoute
  '/recipe/$slug/edit/': typeof RecipeSlugEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ingredient': typeof IngredientIndexRoute
  '/login': typeof LoginIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/recipe': typeof RecipeIndexRoute
  '/register': typeof RegisterIndexRoute
  '/shopping-list': typeof ShoppingListIndexRoute
  '/ingredient/$slug': typeof IngredientSlugIndexRoute
  '/ingredient/add': typeof IngredientAddIndexRoute
  '/recipe/$slug': typeof RecipeSlugIndexRoute
  '/recipe/add': typeof RecipeAddIndexRoute
  '/ingredient/$slug/edit': typeof IngredientSlugEditIndexRoute
  '/recipe/$slug/edit': typeof RecipeSlugEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ingredient/': typeof IngredientIndexRoute
  '/login/': typeof LoginIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/recipe/': typeof RecipeIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/shopping-list/': typeof ShoppingListIndexRoute
  '/ingredient/$slug/': typeof IngredientSlugIndexRoute
  '/ingredient/add/': typeof IngredientAddIndexRoute
  '/recipe/$slug/': typeof RecipeSlugIndexRoute
  '/recipe/add/': typeof RecipeAddIndexRoute
  '/ingredient/$slug/edit/': typeof IngredientSlugEditIndexRoute
  '/recipe/$slug/edit/': typeof RecipeSlugEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ingredient/'
    | '/login/'
    | '/profile/'
    | '/recipe/'
    | '/register/'
    | '/shopping-list/'
    | '/ingredient/$slug/'
    | '/ingredient/add/'
    | '/recipe/$slug/'
    | '/recipe/add/'
    | '/ingredient/$slug/edit/'
    | '/recipe/$slug/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ingredient'
    | '/login'
    | '/profile'
    | '/recipe'
    | '/register'
    | '/shopping-list'
    | '/ingredient/$slug'
    | '/ingredient/add'
    | '/recipe/$slug'
    | '/recipe/add'
    | '/ingredient/$slug/edit'
    | '/recipe/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/ingredient/'
    | '/login/'
    | '/profile/'
    | '/recipe/'
    | '/register/'
    | '/shopping-list/'
    | '/ingredient/$slug/'
    | '/ingredient/add/'
    | '/recipe/$slug/'
    | '/recipe/add/'
    | '/ingredient/$slug/edit/'
    | '/recipe/$slug/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IngredientIndexRoute: typeof IngredientIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  RecipeIndexRoute: typeof RecipeIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  ShoppingListIndexRoute: typeof ShoppingListIndexRoute
  IngredientSlugIndexRoute: typeof IngredientSlugIndexRoute
  IngredientAddIndexRoute: typeof IngredientAddIndexRoute
  RecipeSlugIndexRoute: typeof RecipeSlugIndexRoute
  RecipeAddIndexRoute: typeof RecipeAddIndexRoute
  IngredientSlugEditIndexRoute: typeof IngredientSlugEditIndexRoute
  RecipeSlugEditIndexRoute: typeof RecipeSlugEditIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping-list/': {
      id: '/shopping-list/'
      path: '/shopping-list'
      fullPath: '/shopping-list/'
      preLoaderRoute: typeof ShoppingListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/': {
      id: '/recipe/'
      path: '/recipe'
      fullPath: '/recipe/'
      preLoaderRoute: typeof RecipeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredient/': {
      id: '/ingredient/'
      path: '/ingredient'
      fullPath: '/ingredient/'
      preLoaderRoute: typeof IngredientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/add/': {
      id: '/recipe/add/'
      path: '/recipe/add'
      fullPath: '/recipe/add/'
      preLoaderRoute: typeof RecipeAddIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/$slug/': {
      id: '/recipe/$slug/'
      path: '/recipe/$slug'
      fullPath: '/recipe/$slug/'
      preLoaderRoute: typeof RecipeSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredient/add/': {
      id: '/ingredient/add/'
      path: '/ingredient/add'
      fullPath: '/ingredient/add/'
      preLoaderRoute: typeof IngredientAddIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredient/$slug/': {
      id: '/ingredient/$slug/'
      path: '/ingredient/$slug'
      fullPath: '/ingredient/$slug/'
      preLoaderRoute: typeof IngredientSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/$slug/edit/': {
      id: '/recipe/$slug/edit/'
      path: '/recipe/$slug/edit'
      fullPath: '/recipe/$slug/edit/'
      preLoaderRoute: typeof RecipeSlugEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredient/$slug/edit/': {
      id: '/ingredient/$slug/edit/'
      path: '/ingredient/$slug/edit'
      fullPath: '/ingredient/$slug/edit/'
      preLoaderRoute: typeof IngredientSlugEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IngredientIndexRoute: IngredientIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  RecipeIndexRoute: RecipeIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  ShoppingListIndexRoute: ShoppingListIndexRoute,
  IngredientSlugIndexRoute: IngredientSlugIndexRoute,
  IngredientAddIndexRoute: IngredientAddIndexRoute,
  RecipeSlugIndexRoute: RecipeSlugIndexRoute,
  RecipeAddIndexRoute: RecipeAddIndexRoute,
  IngredientSlugEditIndexRoute: IngredientSlugEditIndexRoute,
  RecipeSlugEditIndexRoute: RecipeSlugEditIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
