RecipeResponseModel:
  type: object
  required:
    - id
    - slug
    - title
    - description
    - time_active
    - time_taken
    - portion_num
    - portion_string
  properties:
    id:
      type: string
      format: uuid
    slug:
      type: string
    title:
      type: string
    description:
      type: string
      nullable: true
    time_taken:
      type: integer
      format: int32
    time_active:
      type: integer
      format: int32
    portion_num:
      type: integer
      format: int32
    portion_string:
      type: string

RecipePatchModel:
  type: object
  properties:
    slug:
      type: string
    title:
      type: string
    description:
      type: string
      nullable: true
    time_taken:
      type: integer
      format: int32
    time_active:
      type: integer
      format: int32
    portion_num:
      type: integer
      format: int32
    portion_string:
      type: string

RecipeStepModel:
  type: object
  required:
    - id
    - position
    - description
  properties:
    id:
      type: string
      format: uuid
    section_name:
      type: string
      nullable: true
    position:
      type: integer
      format: int32
    description:
      type: string

RecipeIngredientModel:
  type: object
  required:
    - id
    - ingredient_id
    - position
    - amount
  properties:
    id:
      type: string
      format: uuid
    ingredient_id:
      type: string
      format: uuid
    section_name:
      type: string
      nullable: true
    position:
      type: integer
      format: int32
    amount:
      type: number
      format: float

RecipeFullResponseModel:
  type: object
  required:
    - id
    - slug
    - title
    - description
    - time_active
    - time_taken
    - portion_num
    - portion_string
    - steps
    - ingredients
  properties:
    id:
      type: string
      format: uuid
    slug:
      type: string
    title:
      type: string
    description:
      type: string
      nullable: true
    time_taken:
      type: integer
      format: int32
    time_active:
      type: integer
      format: int32
    portion_num:
      type: integer
      format: int32
    portion_string:
      type: string
    steps:
      type: array
      items:
        $ref: '#/RecipeStepModel'
    ingredients:
      type: array
      items:
        $ref: '#/RecipeIngredientModel'