export const nutritionFields = [
    { key: "calories", label: "Kalorien", unit: "kcal" },
    { key: "totalFat", label: "Fett gesamt", unit: "g" },
    { key: "fatUnsaturated", label: "davon ungesättigt", unit: "g" },
    { key: "fatSaturated", label: "davon gesättigt", unit: "g" },
    { key: "cholesterol", label: "Cholesterin", unit: "mg" },
    { key: "totalCarbohydrates", label: "Kohlenhydrate gesamt", unit: "g" },
    { key: "totalSugars", label: "davon Zucker", unit: "g" },
    { key: "dietaryFiber", label: "Ballaststoffe", unit: "g" },
    { key: "protein", label: "Eiweiß", unit: "g" },
    { key: "salt", label: "Salz", unit: "g" },
    { key: "water", label: "Wasser", unit: "g" },
    { key: "vitaminA", label: "Vitamin A", unit: "µg" },
    { key: "vitaminB12", label: "Vitamin B12", unit: "µg" },
    { key: "vitaminC", label: "Vitamin C", unit: "mg" },
    { key: "vitaminD", label: "Vitamin D", unit: "µg" },
    { key: "potassium", label: "Kalium", unit: "mg" },
    { key: "sodium", label: "Natrium", unit: "mg" },
    { key: "calcium", label: "Calcium", unit: "mg" },
    { key: "iron", label: "Eisen", unit: "mg" },
    { key: "density", label: "Dichte", unit: "g/ml" },
] as const
