// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingredient.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIngredient = `-- name: CreateIngredient :one
INSERT INTO ingredients (
    slug,
    title
)
VALUES ($1, $2)
RETURNING id, slug, title, calories, totalfat, fatunsaturated, fatsaturated, cholesterol, totalcarbohydrates, totalsugars, dietaryfiber, protein, salt, water, vitamina, vitaminb12, vitaminc, vitamind, potassium, sodium, calcium, iron, density, keywords
`

type CreateIngredientParams struct {
	Slug  string `db:"slug" json:"slug"`
	Title string `db:"title" json:"title"`
}

func (q *Queries) CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, createIngredient, arg.Slug, arg.Title)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Calories,
		&i.Totalfat,
		&i.Fatunsaturated,
		&i.Fatsaturated,
		&i.Cholesterol,
		&i.Totalcarbohydrates,
		&i.Totalsugars,
		&i.Dietaryfiber,
		&i.Protein,
		&i.Salt,
		&i.Water,
		&i.Vitamina,
		&i.Vitaminb12,
		&i.Vitaminc,
		&i.Vitamind,
		&i.Potassium,
		&i.Sodium,
		&i.Calcium,
		&i.Iron,
		&i.Density,
		&i.Keywords,
	)
	return i, err
}

const getIngredient = `-- name: GetIngredient :one
SELECT id, slug, title, calories, totalfat, fatunsaturated, fatsaturated, cholesterol, totalcarbohydrates, totalsugars, dietaryfiber, protein, salt, water, vitamina, vitaminb12, vitaminc, vitamind, potassium, sodium, calcium, iron, density, keywords
FROM ingredients
WHERE id = $1
`

func (q *Queries) GetIngredient(ctx context.Context, id pgtype.UUID) (Ingredient, error) {
	row := q.db.QueryRow(ctx, getIngredient, id)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Calories,
		&i.Totalfat,
		&i.Fatunsaturated,
		&i.Fatsaturated,
		&i.Cholesterol,
		&i.Totalcarbohydrates,
		&i.Totalsugars,
		&i.Dietaryfiber,
		&i.Protein,
		&i.Salt,
		&i.Water,
		&i.Vitamina,
		&i.Vitaminb12,
		&i.Vitaminc,
		&i.Vitamind,
		&i.Potassium,
		&i.Sodium,
		&i.Calcium,
		&i.Iron,
		&i.Density,
		&i.Keywords,
	)
	return i, err
}

const getIngredients = `-- name: GetIngredients :many
SELECT id, slug, title, calories, totalfat, fatunsaturated, fatsaturated, cholesterol, totalcarbohydrates, totalsugars, dietaryfiber, protein, salt, water, vitamina, vitaminb12, vitaminc, vitamind, potassium, sodium, calcium, iron, density, keywords
FROM ingredients
ORDER BY title
`

func (q *Queries) GetIngredients(ctx context.Context) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, getIngredients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Calories,
			&i.Totalfat,
			&i.Fatunsaturated,
			&i.Fatsaturated,
			&i.Cholesterol,
			&i.Totalcarbohydrates,
			&i.Totalsugars,
			&i.Dietaryfiber,
			&i.Protein,
			&i.Salt,
			&i.Water,
			&i.Vitamina,
			&i.Vitaminb12,
			&i.Vitaminc,
			&i.Vitamind,
			&i.Potassium,
			&i.Sodium,
			&i.Calcium,
			&i.Iron,
			&i.Density,
			&i.Keywords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
