// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Ingredient struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	Slug     string      `db:"slug" json:"slug"`
	Title    string      `db:"title" json:"title"`
	Keywords []string    `db:"keywords" json:"keywords"`
}

type Recipe struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	Slug          string      `db:"slug" json:"slug"`
	Title         string      `db:"title" json:"title"`
	Description   pgtype.Text `db:"description" json:"description"`
	TimeTaken     int32       `db:"time_taken" json:"time_taken"`
	TimeActive    int32       `db:"time_active" json:"time_active"`
	PortionNum    int32       `db:"portion_num" json:"portion_num"`
	PortionString string      `db:"portion_string" json:"portion_string"`
}

type RecipeIngredient struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	IngredientID pgtype.UUID `db:"ingredient_id" json:"ingredient_id"`
	RecipeID     pgtype.UUID `db:"recipe_id" json:"recipe_id"`
	RecipeStepID pgtype.UUID `db:"recipe_step_id" json:"recipe_step_id"`
	SectionName  pgtype.Text `db:"section_name" json:"section_name"`
	Position     int32       `db:"position" json:"position"`
	Amount       float64     `db:"amount" json:"amount"`
}

type RecipeStep struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	RecipeID    pgtype.UUID `db:"recipe_id" json:"recipe_id"`
	SectionName pgtype.Text `db:"section_name" json:"section_name"`
	Position    int32       `db:"position" json:"position"`
	Description string      `db:"description" json:"description"`
}

type User struct {
	ID           int32       `db:"id" json:"id"`
	FirstName    pgtype.Text `db:"first_name" json:"first_name"`
	LastName     pgtype.Text `db:"last_name" json:"last_name"`
	PasswordHash string      `db:"password_hash" json:"password_hash"`
	OtpHash      string      `db:"otp_hash" json:"otp_hash"`
}
