// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Ingredient struct {
	ID                 pgtype.UUID   `db:"id" json:"id"`
	Slug               string        `db:"slug" json:"slug"`
	Title              string        `db:"title" json:"title"`
	Calories           int32         `db:"calories" json:"calories"`
	Totalfat           int32         `db:"totalfat" json:"totalfat"`
	Fatunsaturated     int32         `db:"fatunsaturated" json:"fatunsaturated"`
	Fatsaturated       int32         `db:"fatsaturated" json:"fatsaturated"`
	Cholesterol        int32         `db:"cholesterol" json:"cholesterol"`
	Totalcarbohydrates int32         `db:"totalcarbohydrates" json:"totalcarbohydrates"`
	Totalsugars        int32         `db:"totalsugars" json:"totalsugars"`
	Dietaryfiber       int32         `db:"dietaryfiber" json:"dietaryfiber"`
	Protein            int32         `db:"protein" json:"protein"`
	Salt               int32         `db:"salt" json:"salt"`
	Water              int32         `db:"water" json:"water"`
	Vitamina           int32         `db:"vitamina" json:"vitamina"`
	Vitaminb12         int32         `db:"vitaminb12" json:"vitaminb12"`
	Vitaminc           int32         `db:"vitaminc" json:"vitaminc"`
	Vitamind           int32         `db:"vitamind" json:"vitamind"`
	Potassium          int32         `db:"potassium" json:"potassium"`
	Sodium             int32         `db:"sodium" json:"sodium"`
	Calcium            int32         `db:"calcium" json:"calcium"`
	Iron               int32         `db:"iron" json:"iron"`
	Density            pgtype.Float8 `db:"density" json:"density"`
	Keywords           []string      `db:"keywords" json:"keywords"`
}

type Recipe struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	Slug          string      `db:"slug" json:"slug"`
	Title         string      `db:"title" json:"title"`
	Description   pgtype.Text `db:"description" json:"description"`
	TimeTaken     int32       `db:"time_taken" json:"time_taken"`
	TimeActive    int32       `db:"time_active" json:"time_active"`
	PortionNum    int32       `db:"portion_num" json:"portion_num"`
	PortionString string      `db:"portion_string" json:"portion_string"`
}

type RecipeIngredient struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	IngredientID pgtype.UUID `db:"ingredient_id" json:"ingredient_id"`
	RecipeID     pgtype.UUID `db:"recipe_id" json:"recipe_id"`
	RecipeStepID pgtype.UUID `db:"recipe_step_id" json:"recipe_step_id"`
	SectionName  pgtype.Text `db:"section_name" json:"section_name"`
	Position     int32       `db:"position" json:"position"`
	Amount       float64     `db:"amount" json:"amount"`
}

type RecipeStep struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	RecipeID    pgtype.UUID `db:"recipe_id" json:"recipe_id"`
	SectionName pgtype.Text `db:"section_name" json:"section_name"`
	Position    int32       `db:"position" json:"position"`
	Description string      `db:"description" json:"description"`
}

type User struct {
	ID           int32       `db:"id" json:"id"`
	FirstName    pgtype.Text `db:"first_name" json:"first_name"`
	LastName     pgtype.Text `db:"last_name" json:"last_name"`
	PasswordHash string      `db:"password_hash" json:"password_hash"`
	OtpHash      string      `db:"otp_hash" json:"otp_hash"`
}
