// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIngredient = `-- name: CreateIngredient :one
INSERT INTO ingredients (
    slug,
    title
)
VALUES ($1, $2)
RETURNING id, slug, title, keywords
`

type CreateIngredientParams struct {
	Slug  string `db:"slug" json:"slug"`
	Title string `db:"title" json:"title"`
}

func (q *Queries) CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, createIngredient, arg.Slug, arg.Title)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Keywords,
	)
	return i, err
}

const createRecipe = `-- name: CreateRecipe :one
INSERT INTO recipes (
    slug,
    title
)
VALUES ($1,$2)
RETURNING id, slug, title, description, time_taken, time_active, portion_num, portion_string
`

type CreateRecipeParams struct {
	Slug  string `db:"slug" json:"slug"`
	Title string `db:"title" json:"title"`
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, createRecipe, arg.Slug, arg.Title)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.TimeTaken,
		&i.TimeActive,
		&i.PortionNum,
		&i.PortionString,
	)
	return i, err
}

const createRecipeStep = `-- name: CreateRecipeStep :one
INSERT INTO recipe_step (
    section_name,
    position,
    description
)
VALUES ($1,$2,$3)
RETURNING id, recipe_id, section_name, position, description
`

type CreateRecipeStepParams struct {
	SectionName pgtype.Text `db:"section_name" json:"section_name"`
	Position    int32       `db:"position" json:"position"`
	Description string      `db:"description" json:"description"`
}

func (q *Queries) CreateRecipeStep(ctx context.Context, arg CreateRecipeStepParams) (RecipeStep, error) {
	row := q.db.QueryRow(ctx, createRecipeStep, arg.SectionName, arg.Position, arg.Description)
	var i RecipeStep
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.SectionName,
		&i.Position,
		&i.Description,
	)
	return i, err
}

const getIngredient = `-- name: GetIngredient :one
SELECT id, slug, title, keywords
FROM ingredients
WHERE id = $1
`

func (q *Queries) GetIngredient(ctx context.Context, id pgtype.UUID) (Ingredient, error) {
	row := q.db.QueryRow(ctx, getIngredient, id)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Keywords,
	)
	return i, err
}

const getIngredients = `-- name: GetIngredients :many
SELECT id, slug, title, keywords
FROM ingredients
ORDER BY title
`

func (q *Queries) GetIngredients(ctx context.Context) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, getIngredients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Keywords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecipeBySlug = `-- name: GetRecipeBySlug :one
SELECT id, slug, title, description, time_taken, time_active, portion_num, portion_string
FROM recipes
WHERE slug = $1
`

func (q *Queries) GetRecipeBySlug(ctx context.Context, slug string) (Recipe, error) {
	row := q.db.QueryRow(ctx, getRecipeBySlug, slug)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.TimeTaken,
		&i.TimeActive,
		&i.PortionNum,
		&i.PortionString,
	)
	return i, err
}

const getRecipeIngredients = `-- name: GetRecipeIngredients :many
SELECT id, ingredient_id, recipe_id, recipe_step_id, section_name, position, amount
FROM recipe_ingredients
WHERE recipe_id = $1
ORDER BY position
`

func (q *Queries) GetRecipeIngredients(ctx context.Context, recipeID pgtype.UUID) ([]RecipeIngredient, error) {
	rows, err := q.db.Query(ctx, getRecipeIngredients, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecipeIngredient
	for rows.Next() {
		var i RecipeIngredient
		if err := rows.Scan(
			&i.ID,
			&i.IngredientID,
			&i.RecipeID,
			&i.RecipeStepID,
			&i.SectionName,
			&i.Position,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecipeSteps = `-- name: GetRecipeSteps :many
SELECT id, recipe_id, section_name, position, description
FROM recipe_step
WHERE recipe_id = $1
ORDER BY position
`

func (q *Queries) GetRecipeSteps(ctx context.Context, recipeID pgtype.UUID) ([]RecipeStep, error) {
	rows, err := q.db.Query(ctx, getRecipeSteps, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecipeStep
	for rows.Next() {
		var i RecipeStep
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.SectionName,
			&i.Position,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecipes = `-- name: GetRecipes :many
SELECT id, slug, title, description, time_taken, time_active, portion_num, portion_string
FROM recipes
ORDER BY title
`

func (q *Queries) GetRecipes(ctx context.Context) ([]Recipe, error) {
	rows, err := q.db.Query(ctx, getRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.TimeTaken,
			&i.TimeActive,
			&i.PortionNum,
			&i.PortionString,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
