// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipestep.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecipeIngredient = `-- name: CreateRecipeIngredient :one
INSERT INTO recipe_ingredients (
    ingredient_id,
    recipe_id,
    recipe_step_id,
    section_name,
    position,
    amount
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, ingredient_id, recipe_id, recipe_step_id, section_name, position, amount
`

type CreateRecipeIngredientParams struct {
	IngredientID pgtype.UUID `db:"ingredient_id" json:"ingredient_id"`
	RecipeID     pgtype.UUID `db:"recipe_id" json:"recipe_id"`
	RecipeStepID pgtype.UUID `db:"recipe_step_id" json:"recipe_step_id"`
	SectionName  pgtype.Text `db:"section_name" json:"section_name"`
	Position     int32       `db:"position" json:"position"`
	Amount       float64     `db:"amount" json:"amount"`
}

func (q *Queries) CreateRecipeIngredient(ctx context.Context, arg CreateRecipeIngredientParams) (RecipeIngredient, error) {
	row := q.db.QueryRow(ctx, createRecipeIngredient,
		arg.IngredientID,
		arg.RecipeID,
		arg.RecipeStepID,
		arg.SectionName,
		arg.Position,
		arg.Amount,
	)
	var i RecipeIngredient
	err := row.Scan(
		&i.ID,
		&i.IngredientID,
		&i.RecipeID,
		&i.RecipeStepID,
		&i.SectionName,
		&i.Position,
		&i.Amount,
	)
	return i, err
}

const createRecipeStep = `-- name: CreateRecipeStep :one
INSERT INTO recipe_step (
    recipe_id,
    section_name,
    position,
    description
)
VALUES ($1,$2,$3,$4)
RETURNING id, recipe_id, section_name, position, description
`

type CreateRecipeStepParams struct {
	RecipeID    pgtype.UUID `db:"recipe_id" json:"recipe_id"`
	SectionName pgtype.Text `db:"section_name" json:"section_name"`
	Position    int32       `db:"position" json:"position"`
	Description string      `db:"description" json:"description"`
}

func (q *Queries) CreateRecipeStep(ctx context.Context, arg CreateRecipeStepParams) (RecipeStep, error) {
	row := q.db.QueryRow(ctx, createRecipeStep,
		arg.RecipeID,
		arg.SectionName,
		arg.Position,
		arg.Description,
	)
	var i RecipeStep
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.SectionName,
		&i.Position,
		&i.Description,
	)
	return i, err
}

const getRecipeIngredients = `-- name: GetRecipeIngredients :many
SELECT id, ingredient_id, recipe_id, recipe_step_id, section_name, position, amount
FROM recipe_ingredients
WHERE recipe_id = $1
ORDER BY position
`

func (q *Queries) GetRecipeIngredients(ctx context.Context, recipeID pgtype.UUID) ([]RecipeIngredient, error) {
	rows, err := q.db.Query(ctx, getRecipeIngredients, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecipeIngredient
	for rows.Next() {
		var i RecipeIngredient
		if err := rows.Scan(
			&i.ID,
			&i.IngredientID,
			&i.RecipeID,
			&i.RecipeStepID,
			&i.SectionName,
			&i.Position,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecipeSteps = `-- name: GetRecipeSteps :many
SELECT id, recipe_id, section_name, position, description
FROM recipe_step
WHERE recipe_id = $1
ORDER BY position
`

func (q *Queries) GetRecipeSteps(ctx context.Context, recipeID pgtype.UUID) ([]RecipeStep, error) {
	rows, err := q.db.Query(ctx, getRecipeSteps, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecipeStep
	for rows.Next() {
		var i RecipeStep
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.SectionName,
			&i.Position,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
