// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipe.sql

package repository

import (
	"context"
)

const createRecipe = `-- name: CreateRecipe :one
INSERT INTO recipes (
    slug,
    title
)
VALUES ($1,$2)
RETURNING id, slug, title, description, time_taken, time_active, portion_num, portion_string
`

type CreateRecipeParams struct {
	Slug  string `db:"slug" json:"slug"`
	Title string `db:"title" json:"title"`
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, createRecipe, arg.Slug, arg.Title)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.TimeTaken,
		&i.TimeActive,
		&i.PortionNum,
		&i.PortionString,
	)
	return i, err
}

const getRecipeBySlug = `-- name: GetRecipeBySlug :one
SELECT id, slug, title, description, time_taken, time_active, portion_num, portion_string
FROM recipes
WHERE slug = $1
`

func (q *Queries) GetRecipeBySlug(ctx context.Context, slug string) (Recipe, error) {
	row := q.db.QueryRow(ctx, getRecipeBySlug, slug)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.TimeTaken,
		&i.TimeActive,
		&i.PortionNum,
		&i.PortionString,
	)
	return i, err
}

const getRecipes = `-- name: GetRecipes :many
SELECT id, slug, title, description, time_taken, time_active, portion_num, portion_string
FROM recipes
ORDER BY title
`

func (q *Queries) GetRecipes(ctx context.Context) ([]Recipe, error) {
	rows, err := q.db.Query(ctx, getRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.TimeTaken,
			&i.TimeActive,
			&i.PortionNum,
			&i.PortionString,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
